version: "3.9"
services:
  majestic:
    build: .
    container_name: majestic
    volumes:
      - ./profiles:/app/profiles
      - ./data:/app/data
    stdin_open: true
    tty: true
    restart: unless-stopped
