"""
majestic setup   — first-run wizard
majestic model   — switch LLM provider/model
majestic config  — get/set config values
majestic doctor  — diagnose configuration
"""
import os
import sys

from majestic.cli.display import ask, choose, ok, warn, err, info, B, R, G, Y, DIM, C
from majestic.constants import MAJESTIC_HOME, CONFIG_FILE, ENV_FILE
from majestic import config as cfg

_ANTHROPIC_MODELS = [
    "claude-sonnet-4-6",
    "claude-opus-4-7",
    "claude-haiku-4-5-20251001",
]

_OPENROUTER_MODELS = [
    "anthropic/claude-sonnet-4-6",
    "openai/gpt-4o",
    "google/gemini-2.5-pro",
    "meta-llama/llama-3.1-70b-instruct",
]


# ── Helpers ────────────────────────────────────────────────────────────────────

def _write_env(env: dict) -> None:
    MAJESTIC_HOME.mkdir(parents=True, exist_ok=True)
    lines = ["# Majestic Agent — API keys and secrets", "# Generated by `majestic setup`", ""]
    for k, v in env.items():
        lines.append(f"{k}={v}")
    ENV_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _read_env() -> dict:
    if not ENV_FILE.exists():
        return {}
    result = {}
    for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        result[k.strip()] = v.strip()
    return result


# ── Setup wizard ───────────────────────────────────────────────────────────────

def run_setup() -> None:
    print(f"\n  {B}Majestic Setup Wizard{R}")
    print(f"  {DIM}Configuration will be saved to {MAJESTIC_HOME}{R}\n")

    if cfg.is_configured():
        raw = ask("Already configured. Reconfigure?", "n").lower()
        if raw not in ("y", "yes"):
            ok("Setup cancelled.")
            return

    env  = _read_env()
    data = cfg.load()

    # ── LLM Provider ──────────────────────────────────────────────────────────
    current_provider = data.get("llm", {}).get("provider", "anthropic")
    providers = ["anthropic", "openrouter"]
    default_idx = providers.index(current_provider) if current_provider in providers else 0
    pidx = choose("LLM Provider", providers, default=default_idx)
    provider = providers[pidx]

    # ── API Key ───────────────────────────────────────────────────────────────
    if provider == "anthropic":
        current_key = env.get("ANTHROPIC_API_KEY", "")
        hint = f"***{current_key[-4:]}" if current_key else ""
        key = ask("Anthropic API key", hint)
        if key and not key.startswith("***"):
            env["ANTHROPIC_API_KEY"] = key
        elif not key and not current_key:
            warn("No API key provided — you can add it later to ~/.majestic-agent/.env")
    else:
        current_key = env.get("OPENROUTER_API_KEY", "")
        hint = f"***{current_key[-4:]}" if current_key else ""
        key = ask("OpenRouter API key", hint)
        if key and not key.startswith("***"):
            env["OPENROUTER_API_KEY"] = key
        elif not key and not current_key:
            warn("No API key provided — you can add it later to ~/.majestic-agent/.env")

    # ── Model ─────────────────────────────────────────────────────────────────
    model_list = _ANTHROPIC_MODELS if provider == "anthropic" else _OPENROUTER_MODELS
    current_model = data.get("llm", {}).get("model", model_list[0])
    midx = model_list.index(current_model) if current_model in model_list else 0
    midx = choose("Model", model_list + ["Enter manually"], default=midx)
    if midx == len(model_list):
        model = ask("Model name")
    else:
        model = model_list[midx]

    data["llm"] = {"provider": provider, "model": model}

    # ── Telegram ─────────────────────────────────────────────────────────────
    print(f"\n  {B}Telegram{R} {DIM}(optional — skip with Enter){R}")
    tg_token = ask("Bot token", env.get("TELEGRAM_BOT_TOKEN", ""))
    if tg_token:
        env["TELEGRAM_BOT_TOKEN"] = tg_token
        tg_ids = ask(
            "Allowed user IDs (comma-separated)",
            ",".join(str(i) for i in data.get("telegram", {}).get("allowed_user_ids", [])),
        )
        ids = [int(x.strip()) for x in tg_ids.split(",") if x.strip().isdigit()]
        data.setdefault("telegram", {})["allowed_user_ids"] = ids

    # ── Optional API keys ────────────────────────────────────────────────────
    print(f"\n  {B}Optional keys{R} {DIM}(press Enter to skip){R}")
    for key_name, label in [
        ("TAVILY_API_KEY",    "Tavily (better web search)"),
        ("ALPHAVANTAGE_KEY",  "AlphaVantage (stocks)"),
        ("FINNHUB_KEY",       "Finnhub (stocks)"),
    ]:
        current = env.get(key_name, "")
        hint = f"***{current[-4:]}" if current else ""
        val = ask(label, hint)
        if val and not val.startswith("***"):
            env[key_name] = val

    # ── Language / Currency ───────────────────────────────────────────────────
    print()
    data["language"] = ask("Response language (EN, RU, ES, …)", data.get("language", "EN")).upper()
    data["currency"] = ask("Currency (USD, EUR, …)", data.get("currency", "USD")).upper()

    # ── Save ──────────────────────────────────────────────────────────────────
    MAJESTIC_HOME.mkdir(parents=True, exist_ok=True)
    for d in ("memory", "skills", "exports", "workspace"):
        (MAJESTIC_HOME / d).mkdir(exist_ok=True)

    cfg.save(data)
    _write_env(env)

    print(f"\n  {G}✓ Configuration saved to {MAJESTIC_HOME}{R}")
    print(f"  {DIM}Run `majestic doctor` to verify everything is working.{R}\n")


# ── Model switcher ─────────────────────────────────────────────────────────────

def select_model() -> None:
    data     = cfg.load()
    provider = data.get("llm", {}).get("provider", "anthropic")
    current  = data.get("llm", {}).get("model", "")

    print(f"\n  {B}Current:{R} {provider} / {current}\n")

    pidx = choose("Provider", ["anthropic", "openrouter"], default=0 if provider == "anthropic" else 1)
    provider = ["anthropic", "openrouter"][pidx]

    model_list = _ANTHROPIC_MODELS if provider == "anthropic" else _OPENROUTER_MODELS
    midx = model_list.index(current) if current in model_list else 0
    midx = choose("Model", model_list + ["Enter manually"], default=midx)
    if midx == len(model_list):
        model = ask("Model name")
    else:
        model = model_list[midx]

    cfg.set_value("llm.provider", provider)
    cfg.set_value("llm.model", model)
    ok(f"Model set to {B}{provider} / {model}{R}")


# ── Config get/set ─────────────────────────────────────────────────────────────

def config_cmd(args: list[str]) -> None:
    if not args:
        _show_config()
        return

    sub = args[0].lower()
    if sub == "get":
        if len(args) < 2:
            err("Usage: majestic config get <key>")
            return
        val = cfg.get(args[1])
        print(f"  {args[1]} = {val}")

    elif sub == "set":
        if len(args) < 3:
            err("Usage: majestic config set <key> <value>")
            return
        cfg.set_value(args[1], args[2])
        ok(f"Set {args[1]} = {args[2]}")

    else:
        err(f"Unknown subcommand: {sub}. Use get or set.")


def _show_config() -> None:
    data = cfg.load()
    env  = _read_env()
    print(f"\n  {B}Config{R} {DIM}({CONFIG_FILE}){R}\n")
    _print_dict(data, indent=2)
    print(f"\n  {B}Keys set in .env:{R}")
    for k, v in env.items():
        masked = f"***{v[-4:]}" if len(v) > 8 else "***"
        print(f"    {k} = {DIM}{masked}{R}")
    print()


def _print_dict(d: dict, indent: int = 0) -> None:
    pad = " " * indent
    for k, v in d.items():
        if isinstance(v, dict):
            print(f"  {pad}{B}{k}:{R}")
            _print_dict(v, indent + 2)
        else:
            print(f"  {pad}{DIM}{k}:{R} {v}")


# ── Doctor ─────────────────────────────────────────────────────────────────────

def run_doctor() -> None:
    print(f"\n  {B}Majestic Doctor{R}\n")
    problems = 0

    # Python version
    v = sys.version_info
    if v >= (3, 11):
        ok(f"Python {v.major}.{v.minor}.{v.micro}")
    else:
        err(f"Python {v.major}.{v.minor} — need 3.11+")
        problems += 1

    # MAJESTIC_HOME
    if MAJESTIC_HOME.exists():
        ok(f"MAJESTIC_HOME  {DIM}{MAJESTIC_HOME}{R}")
    else:
        warn(f"MAJESTIC_HOME not found: {MAJESTIC_HOME}  →  run `majestic setup`")
        problems += 1

    # config.yaml
    if CONFIG_FILE.exists():
        try:
            import yaml
            yaml.safe_load(CONFIG_FILE.read_text())
            ok("config.yaml  valid")
        except Exception as e:
            err(f"config.yaml  parse error: {e}")
            problems += 1
    else:
        warn("config.yaml not found  →  run `majestic setup`")
        problems += 1

    # .env
    if ENV_FILE.exists():
        ok(".env  found")
    else:
        warn(".env not found  →  run `majestic setup`")
        problems += 1

    # LLM key
    cfg.load_env()
    provider = cfg.get("llm.provider", "anthropic")
    if provider == "anthropic":
        key = os.environ.get("ANTHROPIC_API_KEY", "")
        if key:
            ok(f"ANTHROPIC_API_KEY  set ({DIM}***{key[-4:]}{R})")
        else:
            err("ANTHROPIC_API_KEY  not set  →  add to ~/.majestic-agent/.env")
            problems += 1
    elif provider == "openrouter":
        key = os.environ.get("OPENROUTER_API_KEY", "")
        if key:
            ok(f"OPENROUTER_API_KEY  set ({DIM}***{key[-4:]}{R})")
        else:
            err("OPENROUTER_API_KEY  not set  →  add to ~/.majestic-agent/.env")
            problems += 1

    # LLM reachability
    _check_llm(provider)

    # Summary
    print()
    if problems == 0:
        print(f"  {G}{B}All checks passed.{R}\n")
    else:
        print(f"  {Y}{B}{problems} issue(s) found.{R}  Run `majestic setup` to fix.\n")


def _check_llm(provider: str) -> None:
    try:
        if provider == "anthropic":
            import anthropic
            client = anthropic.Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))
            client.models.list()
            ok("Anthropic API  reachable")
        elif provider == "openrouter":
            import requests
            r = requests.get(
                "https://openrouter.ai/api/v1/models",
                headers={"Authorization": f"Bearer {os.environ.get('OPENROUTER_API_KEY', '')}"},
                timeout=5,
            )
            if r.status_code == 200:
                ok("OpenRouter API  reachable")
            else:
                warn(f"OpenRouter API  HTTP {r.status_code}")
    except ImportError as e:
        warn(f"LLM check skipped — missing package: {e}")
    except Exception as e:
        warn(f"LLM API  unreachable: {e}")
