"""
Interactive CLI channel.

Reads user input from stdin using asyncio (non-blocking), detects file
attachments inline, and renders agent responses via Rich when available.
"""

from __future__ import annotations

import asyncio
import os
import sys
from typing import TYPE_CHECKING

from .base import BaseChannel

# ---------------------------------------------------------------------------
# Optional Rich support — graceful degradation when not installed
# ---------------------------------------------------------------------------

try:
    from rich.console import Console as _Console
    from rich.markdown import Markdown as _Markdown

    _rich_console = _Console()
    _RICH_AVAILABLE = True
except ImportError:  # pragma: no cover
    _rich_console = None  # type: ignore[assignment]
    _RICH_AVAILABLE = False

try:
    from prompt_toolkit import PromptSession as _PromptSession
    from prompt_toolkit.completion import Completer as _Completer, Completion as _Completion
    from prompt_toolkit.styles import Style as _Style
    from prompt_toolkit.formatted_text import ANSI as _ANSI
    _PROMPT_TOOLKIT = True
except ImportError:
    _PROMPT_TOOLKIT = False

# ---------------------------------------------------------------------------
# File-path heuristics
# ---------------------------------------------------------------------------

_ATTACHMENT_EXTENSIONS = {
    ".txt", ".md", ".pdf", ".docx", ".doc",
    ".py", ".js", ".ts", ".json", ".yaml", ".yml",
    ".csv", ".html", ".htm", ".xml",
    ".png", ".jpg", ".jpeg", ".gif", ".svg",
    ".zip", ".tar", ".gz",
}

_ACCENT  = "\033[38;2;217;87;103m"
_RESET   = "\033[0m"
_PROMPT  = f"{_ACCENT}>{_RESET} "

_SYSTEM_COMPLETIONS = ["/help", "/skills", "/tools", "/research", "/briefing", "/agents", "/memory", "/budget", "/new", "/quit"]

if _PROMPT_TOOLKIT:
    class _SlashCompleter(_Completer):
        """Completer that holds a reference to a mutable list so updates are instant."""

        def __init__(self, completions: list[str]) -> None:
            self._completions = completions  # shared mutable reference

        def get_completions(self, document, complete_event):
            text = document.text_before_cursor
            if not text.startswith("/"):
                return
            for cmd in self._completions:
                if cmd.startswith(text):
                    yield _Completion(
                        cmd,
                        start_position=-len(text),
                        display=cmd,
                    )

    _COMPLETION_STYLE = _Style.from_dict({
        "completion-menu":                    "bg:default",
        "completion-menu.completion":         "fg:#555555 bg:default",
        "completion-menu.completion.current": "fg:#d95767 bold bg:default",
        "scrollbar.background":               "bg:default",
        "scrollbar.button":                   "bg:default",
        "scrollbar.arrow":                    "bg:default",
    })


def _extract_attachments(text: str) -> tuple[str, list[str]]:
    """Parse *text* for embedded file references.

    Heuristics (applied line-by-line):
    1. A line that starts with ``file:`` — strip the prefix and treat the rest
       as a file path.
    2. A standalone line whose final token ends with a known file extension
       AND that path actually exists on disk.

    Returns
    -------
    (clean_text, attachments)
        *clean_text* has the file-reference lines removed.
        *attachments* is the list of resolved paths (may be empty).
    """
    clean_lines: list[str] = []
    attachments: list[str] = []

    for line in text.splitlines():
        stripped = line.strip()

        if stripped.startswith("file:"):
            path = stripped[len("file:"):].strip()
            attachments.append(path)
            # Do not include the raw "file:" directive in the clean text.
            continue

        # Check whether the last whitespace-separated token looks like a path.
        parts = stripped.split()
        if parts:
            last_token = parts[-1]
            _, ext = os.path.splitext(last_token)
            if ext.lower() in _ATTACHMENT_EXTENSIONS and os.path.exists(last_token):
                attachments.append(last_token)
                # Keep the text but the caller can decide how to handle it.

        clean_lines.append(line)

    return "\n".join(clean_lines).strip(), attachments


class CLIChannel(BaseChannel):
    """Interactive terminal channel backed by asyncio stdin reads.

    Parameters
    ----------
    session_id:
        A stable string identifier for this CLI session (e.g. a UUID or
        timestamp-based string generated by the launcher).
    """

    def __init__(self, session_id: str) -> None:
        self.session_id = session_id
        self._pending_attachments: list[str] = []
        self._pt_session = None  # created lazily on first receive()
        # Mutable list shared with the completer — modify IN-PLACE to update live
        self._completions: list[str] = list(_SYSTEM_COMPLETIONS)

    def set_skill_completions(self, skill_names: list[str]) -> None:
        """Register profile skill names as /skill-name completions."""
        self._completions.clear()
        self._completions.extend(_SYSTEM_COMPLETIONS)
        existing = set(_SYSTEM_COMPLETIONS)
        self._completions.extend(
            f"/{n}" for n in skill_names if n and f"/{n}" not in existing
        )

    # ------------------------------------------------------------------
    # BaseChannel interface
    # ------------------------------------------------------------------

    async def receive(self) -> dict:
        """Show a prompt, read a line, detect attachments."""
        if self._pt_session is None and _PROMPT_TOOLKIT:
            try:
                self._pt_session = _PromptSession(
                    completer=_SlashCompleter(self._completions),
                    complete_while_typing=True,
                    style=_COMPLETION_STYLE,
                )
            except Exception:
                pass  # no console — fall back to plain readline

        if self._pt_session is not None:
            raw = await self._pt_session.prompt_async(_ANSI(_PROMPT))
        else:
            sys.stdout.write(_PROMPT)
            sys.stdout.flush()
            loop = asyncio.get_event_loop()
            raw = await loop.run_in_executor(None, sys.stdin.readline)
            if not raw:
                raise EOFError
            raw = raw.rstrip("\n")

        text, attachments = _extract_attachments(raw)
        all_attachments = self._pending_attachments + attachments
        self._pending_attachments = []

        return {
            "text": text,
            "attachments": all_attachments,
            "session_id": self.session_id,
        }

    async def send(self, message: str) -> None:
        """Print *message* to stdout using Rich Markdown when available."""
        if _RICH_AVAILABLE and _rich_console is not None:
            try:
                from rich.padding import Padding
                _rich_console.print(Padding(_Markdown(message.strip()), (0, 0, 1, 2)))
            except Exception:
                _rich_console.print(_Markdown(message))
        else:
            indented = "\n".join("  " + ln for ln in message.splitlines())
            print(indented)

    async def send_stream(self, token: str) -> None:
        """Write *token* directly to stdout without buffering a newline."""
        sys.stdout.write(token)
        sys.stdout.flush()
