"""
Interactive CLI channel.

Reads user input from stdin using asyncio (non-blocking), detects file
attachments inline, and renders agent responses via Rich when available.
"""

from __future__ import annotations

import asyncio
import os
import sys
from typing import TYPE_CHECKING

from .base import BaseChannel

# ---------------------------------------------------------------------------
# Optional Rich support — graceful degradation when not installed
# ---------------------------------------------------------------------------

try:
    from rich.console import Console as _Console
    from rich.markdown import Markdown as _Markdown

    _rich_console = _Console()
    _RICH_AVAILABLE = True
except ImportError:  # pragma: no cover
    _rich_console = None  # type: ignore[assignment]
    _RICH_AVAILABLE = False

# ---------------------------------------------------------------------------
# File-path heuristics
# ---------------------------------------------------------------------------

_ATTACHMENT_EXTENSIONS = {
    ".txt", ".md", ".pdf", ".docx", ".doc",
    ".py", ".js", ".ts", ".json", ".yaml", ".yml",
    ".csv", ".html", ".htm", ".xml",
    ".png", ".jpg", ".jpeg", ".gif", ".svg",
    ".zip", ".tar", ".gz",
}

_PROMPT = "> "


def _extract_attachments(text: str) -> tuple[str, list[str]]:
    """Parse *text* for embedded file references.

    Heuristics (applied line-by-line):
    1. A line that starts with ``file:`` — strip the prefix and treat the rest
       as a file path.
    2. A standalone line whose final token ends with a known file extension
       AND that path actually exists on disk.

    Returns
    -------
    (clean_text, attachments)
        *clean_text* has the file-reference lines removed.
        *attachments* is the list of resolved paths (may be empty).
    """
    clean_lines: list[str] = []
    attachments: list[str] = []

    for line in text.splitlines():
        stripped = line.strip()

        if stripped.startswith("file:"):
            path = stripped[len("file:"):].strip()
            attachments.append(path)
            # Do not include the raw "file:" directive in the clean text.
            continue

        # Check whether the last whitespace-separated token looks like a path.
        parts = stripped.split()
        if parts:
            last_token = parts[-1]
            _, ext = os.path.splitext(last_token)
            if ext.lower() in _ATTACHMENT_EXTENSIONS and os.path.exists(last_token):
                attachments.append(last_token)
                # Keep the text but the caller can decide how to handle it.

        clean_lines.append(line)

    return "\n".join(clean_lines).strip(), attachments


class CLIChannel(BaseChannel):
    """Interactive terminal channel backed by asyncio stdin reads.

    Parameters
    ----------
    session_id:
        A stable string identifier for this CLI session (e.g. a UUID or
        timestamp-based string generated by the launcher).
    """

    def __init__(self, session_id: str) -> None:
        self.session_id = session_id
        self._pending_attachments: list[str] = []
        self._loop: asyncio.AbstractEventLoop | None = None

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    async def _read_line(self) -> str:
        """Read one line from stdin without blocking the event loop."""
        loop = asyncio.get_event_loop()
        # Use run_in_executor so that the blocking readline does not stall
        # other coroutines scheduled on the same loop.
        line: str = await loop.run_in_executor(None, sys.stdin.readline)
        return line

    # ------------------------------------------------------------------
    # BaseChannel interface
    # ------------------------------------------------------------------

    async def receive(self) -> dict:
        """Show a prompt, read a line, detect attachments.

        Returns
        -------
        dict with keys:
            text        (str)       — user's text (file references stripped).
            attachments (list[str]) — file paths found in the input.
            session_id  (str)       — this channel's session identifier.
        """
        # Write the prompt without a trailing newline.
        sys.stdout.write(_PROMPT)
        sys.stdout.flush()

        raw = await self._read_line()

        # Handle EOF (e.g. piped input finished, Ctrl-D).
        if not raw:
            return {"text": "", "attachments": [], "session_id": self.session_id}

        raw = raw.rstrip("\n")
        text, attachments = _extract_attachments(raw)

        # Merge with any attachments queued from previous interactions.
        all_attachments = self._pending_attachments + attachments
        self._pending_attachments = []

        return {
            "text": text,
            "attachments": all_attachments,
            "session_id": self.session_id,
        }

    async def send(self, message: str) -> None:
        """Print *message* to stdout using Rich Markdown when available."""
        if _RICH_AVAILABLE and _rich_console is not None:
            # Render Markdown so headings, code blocks, and emphasis look nice.
            _rich_console.print(_Markdown(message))
        else:
            print(message)

    async def send_stream(self, token: str) -> None:
        """Write *token* directly to stdout without buffering a newline."""
        sys.stdout.write(token)
        sys.stdout.flush()
